<?php

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\layout_builder\Entity\LayoutBuilderEntityViewDisplay;
use Drupal\block_content\Entity\BlockContent;

/**
 * Implements hook_block_view_BASE_BLOCK_ID_alter().
 */
function athora_layout_builder_block_content_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  // Remove contextual links when block isn't reusable.
  if ($display instanceof LayoutBuilderEntityViewDisplay && $entity instanceof BlockContent && $entity->isReusable() === FALSE) {
    unset($build['#contextual_links']);
  }
}