<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function tbn_search_google_analytics_form_search_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  Drupal::service('tbn_search_google_analytics.search_page_alter_form')->alterForm($form, $form_state, $form_id);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function tbn_search_google_analytics_form_search_modal_block_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  Drupal::service('tbn_search_google_analytics.search_modal_block_alter_form')->alterForm($form, $form_state, $form_id);
}
