<?php

/**
 * Contains all hook implementations for this module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_field_widget_WIDGET_TYPE_form_alter().
 */
function athora_link_field_widget_link_default_form_alter(&$element, FormStateInterface $form_state, $context) {
  // Token support.
  if (\Drupal::moduleHandler()->moduleExists('token')) {
    $tokens = [
      '#title' => t('Tokens'),
      '#type' => 'container',
    ];
    $token_types = [];
    /** @var \Drupal\Core\Entity\EntityBase $entity */
    if ($entity = $form_state->getFormObject()->getEntity()) {
      $token_types[] = $entity->getEntityTypeId();
    }
    $tokens['help'] = [
      '#theme' => 'token_tree_link',
      '#token_types' => $token_types,
      '#dialog' => TRUE,
    ];
    $element['tokens'] = $tokens;
  }
}
